[project]
name = "mcp_server_mac"
version = "0.0.1"
description = "An MCP Server that Returns the MAC Address."
dependencies = [
    "mcp>=1.4.1",
]

[project.scripts]
mcp-server-mac = "mcp_server_mac:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"